# Generated by Django 3.2.5 on 2022-12-15 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_alter_segment_mean_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
