# Generated by Django 3.2.5 on 2022-12-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_description_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='date',
            field=models.DateField(),
        ),
    ]
